### ISSUE TITLE
Atualizar estilos do componente de Switch

### ISSUE THREAD

**Issue by Alecell** [Alecell/octopost#115]
O componente de Switch existente deve ser atualizado para se alinhar com as novas cores do layout.

Ele deve:
- Ser roxo quando ativo
- Ser cinza quando desativado
- Possuir os icones internos do Switch
- Apresentar os efeitos de hover/active conforme pertinentes
- Estado de erro

![Image](https://github.com/Alecell/octopost/assets/13935760/fa60aabc-4592-413f-996e-039b21a65b24)

![Image](https://github.com/Alecell/octopost/assets/13935760/8d3a6ced-496c-476f-a0f3-c0e1bd5f7cf0)

**Comment by hxsggsz** [comment]
It's necessary to add outline on this component for acessibility, he doesn't have it now
