### ISSUE TITLE
Button Component

### ISSUE THREAD

**Issue by Alecell** [Alecell/octopost#118]
Como na aplicação como um todo teremos vários usos de botões, nada mais justo que criar um componente de botão altamente reutilizavel.

Esse componente deve ser hardmente genérico e de facil utilização.

Os botões devem suportar o evento `onClick` para que saibamos quando ele foi clicado.

Para melhor entendimento de como é o como é esperado o resultado consulte: https://mui.com/material-ui/react-button/

Não esqueça de todas as questões que o botão tem como wriple, hover, active e etc.

Exemplos de uso:
_Os botões devem aceitar children_
```tsx
<Button>Enviar</Button>
```

_Botões devem suportar a troca de cor baseada no thema sem necessidade de css_
```tsx
<Button color="primary">Enviar</Button>
```

_Botões devem suportar a troca de cor baseada no thema sem necessidade de css_
```tsx
<Button color="secondary">Enviar</Button>
```

_Botões devem suportar a troca de tipo, como contained, outlined e text_
```tsx
<Button variant="contained">Enviar</Button>
```

_Botões devem suportar a troca de tipo e cor simultaneamente_
```tsx
<Button variant="outlined" color="primary">Enviar</Button>
```

_Botões devem suportar estado de disabled onde eles **não vai ser clicaveis**_
```tsx
<Button disabled>Enviar</Button>
```

_Botões devem suportar a propriedade circle, quando usada o botão vira uma versão circular de um botão_
Nesse caso o botão **não suporta** children, apenas a propriedade `icon`
```tsx
<Button icon="facebook" circle />
```

_Botões do tipo **circle** tambem devem suportar as propriedades color e variant_
```tsx
<Button variant="outlined" color="primery" icon="facebook" circle />
```

_Botões devem suportar override de css quando necessario_
```tsx
<Button variant="outlined" color="primery" icon="facebook" circle className={scss.shade} />
```

Botões:

![Image](https://github.com/Alecell/octopost/assets/13935760/f73cdc15-8352-46d7-9c03-830db683d9a4)

![Image](https://github.com/Alecell/octopost/assets/13935760/9f7868c8-54a5-42c1-a6e9-aec6778e7dcd)

![Image](https://github.com/Alecell/octopost/assets/13935760/3207835f-6389-4731-9f33-5e96f8e43778)

![Image](https://github.com/Alecell/octopost/assets/13935760/072311de-dd0e-43e2-a8bb-040f0d1d4fa1)

**Comment by leandrokzu** [comment]
Pessoal, vou pegar essa task.
