### ISSUE TITLE
create tests for Tabber component #138 

### ISSUE THREAD

**Issue by kingjotaro** [Alecell/octopost#142]
## [Issue Title]

_label: [bug]

assignees: [kingjotaro]

<details open> 
  <summary>
  the jest doesn't recognize the path alias that we use, because of that while this itsn't fixed we cannot create the tests for the component. When this issue be fixed create the tests properly
  </summary>

**Comment by flaviafreirec** [comment]
o kingjotaro nao assinou a issue
