### ISSUE TITLE
ladle doesn't recognize the base.scss styles

### ISSUE THREAD

**Issue by hxsggsz** [Alecell/octopost#149]
## ladle doesn't recognize the base.scss styles

_label: bug
<br>
assignees: @aalmeida00 @PiluVitu 

<details open> 
  <summary>
    <b>Description</b>
  </summary>
   for some reason, the ladle its not been recognized by ladle, there is a configuration inside the ladle that resolve this problem.
</details>

<br>

<details> 
  <summary>
    <b>Visual information</b>
  </summary>

![image](https://github.com/Alecell/octopost/assets/103784814/3248967d-f950-4bc1-b5d5-7b941a3c5fd8)

![image](https://github.com/Alecell/octopost/assets/103784814/a48918f9-d23b-42dc-9528-f405a03fddcd)

</details>

**Comment by PiluVitu** [comment]
Bota eu ae
