### ISSUE TITLE
Error Boundaries

### ISSUE THREAD

**Issue by GabrielTrindadeC** [Alecell/octopost#177]
## Error Boundaries

_label: [error trace]
<br>
assignees: [assignee_username]_

<details open> 
  <summary>
    <b>Description</b>
  </summary>
   Criar componente de error boundary para capturar erros não mapeados/descobertos.
</details>

**Comment by Sherlockzen** [comment]
Opa, tenho interesse nessa aqui!

**Comment by Sherlockzen** [comment]
![image](https://github.com/Alecell/octopost/assets/90076846/37ec21af-95c8-4d90-9974-1a218cafd565)

Galera consegui criar o componente e a princípio ele se comporta dessa forma, ele pode receber um componente no seu fallback e ai renderizar quando ocorrer um erro. Minha dúvida seria se nesse mesmo componente já seria pra ter a ui que será renderizada na tela? Ou no caso isso seria outro componente?
