### ISSUE TITLE
Componente de preview

### ISSUE THREAD

**Issue by Alecell** [Alecell/octopost#178]
<details open> 
  <summary>
    <b>Description</b>
  </summary>
  O componente de preview será derivado do módulo, entretanto precisamos do container cujo será o espaço onde ficarão os previews. **NÃO É PRA FAZER ESSE PREVIEW DO LAYOUT, APENAS CRIAR O ESPAÇO ONDE RESIDIRÁ OS PREVIEWS**

<br>

<details> 
  <summary>
    <b>Visual information</b>
  </summary>

  ![image](https://github.com/Alecell/octopost/assets/13935760/95110a33-d32a-4181-8ca0-2acaee59801d)
</details>

**Comment by PiluVitu** [comment]
Bau bau, simbora

**Comment by PiluVitu** [comment]
Eu quero k k k
