### ISSUE TITLE
First comment

### ISSUE THREAD

**Issue by Alecell** [Alecell/octopost#184]
<details open> 
  <summary>
    <b>Description</b>
  </summary>
   
  Criar o componente de first comment cujo é uma checkbox que abre um MainContent quando for marcado como "ativo".
</details>

<br>

<details> 
  <summary>
    <b>Expected Behavior</b>
  </summary>
  
Quando clicar no checkbox do first comment vamos abrir um main content para preencher o conteúdo do primeiro comentário.
</details>

<br>

<details open> 
  <summary>
    <b>Visual information</b>
  </summary>

![image](https://github.com/Alecell/octopost/assets/13935760/dc8465fa-8ba7-47ad-b033-1a54a05ba78b)

</details>

**Comment by alvarogfn** [comment]
Posso tentar essa?
