### ISSUE TITLE
Corrigir os "warnings" do Jest 

### ISSUE THREAD

**Issue by JpBurgarelli** [Alecell/octopost#193]
## [Corrigir Warnings]

<details open> 
  <summary>
    <b>Description</b>
  </summary>
Corrigir os warnings após rodar o Jest. Há uma imagem anexada a essa Issue como exemplo do que deve ser resolvido.
</details>

<br>

</details>

<br>

<details open> 
  <summary>
    <b>Visual information</b>
  </summary>
  
![image](https://github.com/Alecell/octopost/assets/30197026/d9b17ede-1993-4d1a-96db-311e83c24587)

</details>

<br>

**Comment by PiluVitu** [comment]
Eu queroo!!!

**Comment by PiluVitu** [comment]
Eu quero!!!
