### ISSUE TITLE
Remover warnings de quando roda teste

### ISSUE THREAD

**Issue by Alecell** [Alecell/octopost#196]
<details open> 
  <summary>
    <b>Description</b>
  </summary>

   Quando rodamos `yarn test` existem alguns warnings exibidos no console. É preciso remove-los
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md) 
- escreva: 'eu quero!!!' para ser adicionado a issue

**Comment by Alecell** [comment]
EU QUERO!!!

**Comment by aalmeida00** [comment]
Duplicated https://github.com/Alecell/octopost/issues/193
