### ISSUE TITLE
Criar Workflow para remover assignees de uma issue inativa a mais de 7 dias

### ISSUE THREAD

**Issue by GabrielTrindadeC** [Alecell/octopost#198]

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)
