### ISSUE TITLE
Atualização do `package.json`

### ISSUE THREAD

**Issue by PiluVitu** [Alecell/octopost#205]
<details open> 
  <summary>
    <b>Description</b>
  </summary>
   Viu-se uma necessidade de acidionar dois novas proriedades no package.json: 

   - Engines 
       - Para conseguir especificar a versão do node da aplicação e disparar um erro caso o contributor não esteja na versão especidifcada. 
   - PackageManeger
       - Para conseguir especificar a versão do gerenciador de pacote, no caso yarn, a fim de evitar que contributors com versão anterior tenha dificuldade de contribuir no projeto e que contributors com uma versão acima não consigam atualizar os pacotes para versão mais recente, previnindo uma eventual quebra da aplicação. 
</details>

<br>

<details> 
  <summary>
    <b>Additional Information</b>
  </summary>

    - Recomendo versão v1.22.1 do yarn 

</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)

**Comment by PiluVitu** [comment]
Eu quero !!!

**Comment by PiluVitu** [comment]
Eu quero!!!
