### ISSUE TITLE
arquivo base.scss

### ISSUE THREAD

**Issue by hxsggsz** [Alecell/octopost#23]
o Ale me pediu para criar essa issue pelo seguinte motivo: <a href="https://github.com/Alecell/octopost/pull/6">na pr sobre o toggle social media</a> eu precisaria utilizar padding em uma estilização, porém é necessário usar a medida de estilização "rem" mas enquanto não criarem esse arquivo base, não vai ficar legal o padding. Por isso eu preciso que alguém crie esse arquivo para poder mergear minha pr. Eu não tenho muitos detalhes sobre o que precisa nesse arquivo, mas tem um esquema que eu geralmente gosto de usar nos meus resets de css que é: setar o font-size como 62.5%. Por que esse valor? Eu não lembro exatamente a matemática por  traz desse valor mas basicamente ele converte 10px e 1rem, sendo assim sempre que eu quiser um valor de css que seria por exemplo 24px, eu posso usar o 2.4rem, eu não sei se é exatamente isso que o Ale quer então seria bom conversar com ele antes.

**Comment by aalmeida00** [comment]
Closed on #44
