### ISSUE TITLE
Organizar os containeres da página inicial

### ISSUE THREAD

**Issue by Alecell** [Alecell/octopost#28]
A página inicial deve ter uma estrutura de grid coerente, baseado no nosso "layout" inicial e seus componentes containeres para cada feature.

A pesar de não precisar ser perfeitamente exato, já que não tem como ter precisão com algo tão superficial, precisamos que o grid base seja feito. Ele deve ter esse comportamento:

**Vermelho:** switches
**Amarelo:** tabs
**Blue:** texto inicial
 
![Image](https://user-images.githubusercontent.com/13935760/259249807-9bf6a63c-cfba-4fa2-8918-7e216b755a24.png)

**Comment by aalmeida00** [comment]
Done at https://github.com/Alecell/octopost/pull/41
