### ISSUE TITLE
Lista de redes sociais com scroll interno

### ISSUE THREAD

**Issue by Alecell** [Alecell/octopost#32]
A lista de redes sociais deve possuir um scroll interno, cujo não interfere no tamanho ou scroll da página em si, mas sim apenas no próprio container.

Um bom exemplo de coisa assim é a lista de vídeos quando assistimos uma playlist no youtube:

O ponto é que a lista de itens da playlist é contida no seu próprio espaço e esse deve ser o comportamento da lista de redes sociais.

![Image](https://user-images.githubusercontent.com/13935760/259268947-495e2a7a-b3c6-4b4b-80f4-f6e007d77f16.png)

![Image](https://user-images.githubusercontent.com/13935760/259268996-bdb74f9c-3389-4c5b-9f17-748b1f707b80.png)

**Comment by JpBurgarelli** [comment]
Conforme orientação do @aalmeida00 , já que essa tarefa foi feita @flaviafreirec e o @hxsggsz haveria a possibilidade de eu reaproveitar o que eles fizeram.
