### ISSUE TITLE
mais tags/badges no readme

### ISSUE THREAD

**Issue by hxsggsz** [Alecell/octopost#80]
precisamos adicionar mais badges no nosso readme, colocar algo do tipo: nosso coverage de testes, se os testes estão passando, o link para o nosso discussions e etc. Sintam-se livres para por o que acharem melhor

![image](https://github.com/Alecell/octopost/assets/103784814/bf0bc2e0-9b4e-4c13-b8f2-86ce272e8d78)

## alguns exemplos:

![image](https://github.com/Alecell/octopost/assets/103784814/1073748d-a55c-43bf-88a9-1b79d2c9b629)

## links uteis

https://github-badges.netlify.app
https://www.youtube.com/watch?v=qw3nRdcpZHw
https://www.youtube.com/watch?v=63wxGYIpRY8
https://github.com/alexandresanlim/Badges4-README.md-Profile#-github-stats-

**Comment by aalmeida00** [comment]
Assigned to: @[leandrokzu](https://github.com/leandrokzu)
